create view VW_LISTA_FUNCIONARIOS AS
SELECT NOME, ESPECIALIDADE
FROM FUNCIONARIOS;

#UTILIZANDO A VIEW CRIADA
SELECT * FROM VW_LISTA_FUNCIONARIOS;

#CRIANDO UMA VIEW PARA LISTAR TODOS OS DEPENDENTES
CREATE VIEW VW_LISTA_DEPENDENTES AS
SELECT NOME
FROM DEPENDENTES;

SELECT * FROM VW_LISTA_DEPENDENTES;

CREATE VIEW VW_FUNCIONARIO_COM_DEPENDENTES AS
SELECT FUNCIONARIOS.NOME, DEPENDENTES.NOME
FROM FUNCIONARIOS
INNER JOIN DEENDENTES
ON FUNCIONARIOS.COD_FUNC = DEPENDENTES.COD_FUNC;